package main

// Blank imports that pin pre-existing dependencies in go.mod so `go mod tidy`
// retains them (and their vulnerable transitive closures) for SCA scanners.
//
// Only known-good package paths are used. Modules whose module-path has no
// Go files at the root are referenced via a subpackage. cgo-only and
// abandoned/unresolvable modules are deliberately omitted.
//
// If any single line below fails to resolve, delete just that line and
// re-run `go mod tidy`.

import (
	// --- pre-existing direct deps ---
	_ "gitea.com/lunny/levelqueue"
	_ "gitea.com/macaron/inject"
	_ "gitea.com/macaron/macaron"
	_ "github.com/Unknwon/com"
	_ "github.com/Unknwon/i18n"
	_ "github.com/bradfitz/gomemcache/memcache"
	_ "github.com/emirpasic/gods/utils"
	_ "github.com/gobwas/glob"
	_ "github.com/gophish/gophish/config"
	_ "github.com/jbenet/go-context/io"
	_ "github.com/kballard/go-shellquote"
	_ "github.com/kevinburke/ssh_config"
	_ "github.com/mattn/go-isatty"
	_ "github.com/mcuadros/go-version"
	_ "github.com/mitchellh/go-homedir"
	_ "github.com/sergi/go-diff/diffmatchpatch"
	_ "github.com/shurcooL/sanitized_anchor_name"
	_ "github.com/src-d/gcfg"
	_ "github.com/unknwon/paginater"
	_ "github.com/xanzy/ssh-agent"
	_ "golang.org/x/net/html"
	_ "golang.org/x/sys/cpu"
	_ "gopkg.in/ini.v1"
	_ "gopkg.in/src-d/go-billy.v4/memfs"
	_ "gopkg.in/src-d/go-git.v4"
	_ "gopkg.in/warnings.v0"
	_ "strk.kbt.io/projects/go/libravatar"

	// --- additional known-vulnerable indirect deps promoted to direct ---
	_ "github.com/PuerkitoBio/goquery"
	_ "github.com/RoaringBitmap/roaring"
	_ "github.com/apache/thrift/lib/go/thrift"
	_ "github.com/armon/go-socks5"
	_ "github.com/bgentry/speakeasy"
	_ "github.com/blevesearch/bleve"
	_ "github.com/boombuler/barcode"
	_ "github.com/coreos/bbolt"
	_ "github.com/coreos/go-oidc"
	_ "github.com/coreos/go-semver/semver"
	_ "github.com/cupcake/rdb"
	_ "github.com/docker/go-units"
	_ "github.com/edsrzf/mmap-go"
	_ "github.com/etcd-io/bbolt"
	_ "github.com/gliderlabs/ssh"
	_ "github.com/go-kit/kit/log"
	_ "github.com/go-openapi/analysis"
	_ "github.com/go-openapi/loads"
	_ "github.com/go-openapi/runtime"
	_ "github.com/go-openapi/spec"
	_ "github.com/go-openapi/strfmt"
	_ "github.com/go-openapi/validate"
	_ "github.com/gofrs/uuid"
	_ "github.com/gogits/chardet"
	_ "github.com/gogs/cron"
	_ "github.com/golang/groupcache/lru"
	_ "github.com/golang/mock/gomock"
	_ "github.com/google/go-cmp/cmp"
	_ "github.com/google/go-github/v24/github"
	_ "github.com/google/renameio"
	_ "github.com/gorilla/sessions"
	_ "github.com/grpc-ecosystem/grpc-gateway/runtime"
	_ "github.com/hashicorp/golang-lru"
	_ "github.com/jackc/pgx"
	_ "github.com/jaytaylor/html2text"
	_ "github.com/joho/godotenv"
	_ "github.com/klauspost/compress/flate"
	_ "github.com/klauspost/cpuid"
	_ "github.com/konsorten/go-windows-terminal-sequences"
	_ "github.com/lafriks/xormstore"
	_ "github.com/lib/pq"
	_ "github.com/lunny/dingtalk_webhook"
	_ "github.com/lunny/log"
	_ "github.com/magiconair/properties"
	_ "github.com/mailru/easyjson"
	_ "github.com/markbates/goth"
	_ "github.com/microcosm-cc/bluemonday"
	_ "github.com/nfnt/resize"
	_ "github.com/oliamb/cutter"
	_ "github.com/onsi/ginkgo"
	_ "github.com/onsi/gomega"
	_ "github.com/openzipkin/zipkin-go"
	_ "github.com/pelletier/go-toml"
	_ "github.com/pquerna/cachecontrol"
	_ "github.com/pquerna/otp"
	_ "github.com/prometheus/procfs"
	_ "github.com/prometheus/tsdb"
	_ "github.com/rogpeppe/fastuuid"
	_ "github.com/saintfish/chardet"
	_ "github.com/shurcooL/vfsgen"
	_ "github.com/smartystreets/assertions"
	_ "github.com/spaolacci/murmur3"
	_ "github.com/spf13/afero"
	_ "github.com/spf13/jwalterweatherman"
	_ "github.com/syndtr/goleveldb/leveldb"
	_ "github.com/tstranex/u2f"
	_ "github.com/ugorji/go/codec"
	_ "github.com/willf/bitset"
	_ "github.com/yohcop/openid-go"
	_ "go.etcd.io/bbolt"
	_ "go.mongodb.org/mongo-driver/bson"
	_ "go.opencensus.io/trace"
	_ "google.golang.org/api/option"
	_ "google.golang.org/grpc"
	_ "gopkg.in/alexcesaro/quotedprintable.v3"
	_ "gopkg.in/asn1-ber.v1"
	_ "gopkg.in/gomail.v2"
	_ "gopkg.in/ldap.v3"
	_ "mvdan.cc/xurls/v2"
	_ "xorm.io/builder"
	_ "xorm.io/core"
)
